services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db_url
      - db_users
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_users=${POSTGRES_DB_users}
      - POSTGRES_DB_urlshort=${POSTGRES_DB_urlshort}
    ports:
      - "8000:80"

  db_url:
    image: postgres:15-alpine
    volumes:
      - postgres_data_url:/var/lib/postgresql/data
      - ./db_init_scripts/init_db_url.sql:/docker-entrypoint-initdb.d/init_db_url.sql
    ports:
      # Connect to the database on localhost:5433, but internally it runs on 5432
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_urlshort}

  db_users:
    image: postgres:15-alpine
    volumes:
      - postgres_data_users:/var/lib/postgresql/data
      - ./db_init_scripts/init_db_users.sql:/docker-entrypoint-initdb.d/init_db_users.sql
    ports:
      # Connect to the database on localhost:5434, but internally it runs on 5432
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_users}

volumes:
  postgres_data_url:
  postgres_data_users:
